x-env-defaults: &env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-node: &node
  tty: true
  init: true
  image: node:14.14-alpine
  entrypoint: ["node"]
  working_dir: /monorepo
  volumes:
    - ./monorepo:/monorepo:cached
    - ./monorepo/node_modules:/monorepo/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-node-full: &node-full
  tty: true
  init: true
  image: node:14.14
  working_dir: /monorepo
  volumes:
    - ~/.gitconfig:/etc/gitconfig
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    - ~/.npmrc:/root/.npmrc
    - ./monorepo:/monorepo:cached
    - ./monorepo/node_modules:/monorepo/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

x-ember-defaults: &ember
  tty: true
  init: true
  image: danlynn/ember-cli:3.8.1
  entrypoint: ["bash"]
  working_dir: /myapp
  volumes:
    - ./manage:/myapp:cached
    - ./manage/node_modules:/myapp/node_modules:delegated
    - ember-yarn-cache:/.ember-yarn-cache

x-node-env: &node-env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-ember-env: &ember-env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.ember-yarn-cache

x-mongodb-env: &mongodb-env
  MONGO_DSN: ${MONGO_DSN-mongodb://mongo:27017/lead-management-indm}

x-tenant-env: &tenant-env
  TENANT_KEY: ${TENANT_KEY}

services:
  google-ad-manager:
    tty: true
    image: parameter1/google-ad-manager-graphql-service:v1.1.0
    volumes:
      - ./service-account.json:/service-account.json
    environment:
      JSON_KEY_FILE_PATH: /service-account.json
      NETWORK_CODE: 137873098
      VERSION: v202205

  mongo:
    tty: true
    image: mongo:3.6
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "${SERVER_DB_PORT-9289}:27017"

  redis:
    tty: true
    restart: always
    image: redis:alpine

  manage:
    <<: *ember
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--port", "9285", "--live-reload-port", "9286", "--proxy", "http://server"]
    environment:
      <<: *ember-env
    ports:
      - "9285:9285"
      - "9286:9286"
      - "9287:9287"
    depends_on:
      - server

  exports:
    <<: *node
    working_dir: /monorepo/services/exports
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
    ports:
      - "9290:80"

  server:
    <<: *node
    working_dir: /monorepo/services/server
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*node-env, *mongodb-env, *tenant-env]
      BRIGHTCOVE_ACCOUNT_ID: ${BRIGHTCOVE_ACCOUNT_ID}
      BRIGHTCOVE_APP_ID: ${BRIGHTCOVE_APP_ID}
      BRIGHTCOVE_SECRET: ${BRIGHTCOVE_SECRET}
      EXPOSED_PORT: 9288
      GAM_GRAPHQL_URI: ${GAM_GRAPHQL_URI-http://google-ad-manager}
      HOST_NAME: ${HOST_NAME}
      REDIS_DSN: ${REDIS_DSN-redis://redis:6379/0}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      EXPORTS_S3_BUCKET: ${EXPORTS_S3_BUCKET-lead-management-exports}
      ALLOW_UNREAL_CLICK_CODES: ${ALLOW_UNREAL_CLICK_CODES-0}
    ports:
      - "9288:80"
    depends_on:
      - exports
      - redis
      - mongo
      - google-ad-manager

  migrate:
    <<: *node
    working_dir: /monorepo/packages/migrate
    entrypoint: ["node"]
    command: ["index.js"]
    environment:
      <<: *node-env
      DESTINATION_MONGO_URI: ${MIGRATE_DESTINATION_MONGO_URI}
      SOURCE_MONGO_URI: ${MIGRATE_SOURCE_MONGO_URI}

  bash:
    <<: *node-full
    entrypoint: ["/bin/bash"]

  sync:
    <<: *node
    working_dir: /monorepo/packages/sync
    entrypoint: ["/bin/sh"]
    environment:
      <<: [*node-env, *mongodb-env]

  lambda:
    <<: *node
    working_dir: /monorepo/packages/lambda
    entrypoint: ["/bin/sh"]
    environment:
      <<: [*node-env, *mongodb-env]
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
  mongodb: {}
  yarn-cache: {}
  ember-yarn-cache: {}
